### ISSUE TITLE
Raspbee firmware upgrade HASSOS + RPI3B+ fails

### ISSUE THREAD

**Issue by puk1966** [marthoc/docker-deconz#104]
Hi,

When running upgrade script I get next error:

`# docker run -it --rm --device=/dev/ttyAMA0 --privileged --cap-add=ALL -v /lib/modules:/lib/modules --entrypoint "/firmware-update.sh" marthoc/hassio-addon-deconz-armhf`

   rmmod: ERROR: Module usbserial is builtin.
   GCFFlasher V2_11 (c) dresden elektronik ingenieurtechnik gmbh 2017/12/10
   no device specified use RaspBee (/dev/ttyAMA0)
   using firmware file: /usr/share/deCONZ/firmware/deCONZ_Rpi_0x262f0500.bin.GCF
   Oops: Unable to determine board revision from /proc/cpuinfo

I checked the /proc/cpuinfo file but it's missing the 3 lines "hardware", "revision" and "serial".

Also tried another script which also failed:
```
# docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v 
/lib/modules:/lib/modules -v /sys:/sys marthoc/deconz
```

   Unable to find image 'marthoc/deconz:latest' locally
   latest: Pulling from marthoc/deconz
   docker: no matching manifest for unknown in the manifest list entries.
   See 'docker run --help'.

The problem I guess here is that manifest.yml only supports amd64 and armhf 

```
image: marthoc/deconz:latest
manifests:
  -
    image: marthoc/deconz:amd64
    platform:
      architecture: amd64
      os: linux
  -
    image: marthoc/deconz:armhf
    platform:
      architecture: arm
      variant: armv7l
os: linux
```
 

Is there another way/script or workaround to upgrade on RPI3B+ ?
