### ISSUE TITLE
Device discovered but not showing up.

### ISSUE THREAD

**Issue by jkalousek** [marthoc/docker-deconz#107]
I have ConBee USB stick which I'm using with HA inside Docker, but as I'm not really happy with stability of HA implementation I wanted to try alternative and docker-deconz seems perfect.
To prefix everything:
- ConBee is working with another docker image (HA), so there is no problem with USB communication 
- My lights are visible from windows desktop deconz app, so I assume they should be compatible
- I'm using these lights: https://www.immaxneo.cz/en/home-2/ (GU10)

This is my config for docker-compose:
```
 deconz:
   image: marthoc/deconz
    container_name: deconz
    network_mode: host
    restart: always
    volumes:
      - /docker-data/deconz:/root/.local/share/dresden-elektronik/deCONZ
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyUSB_ZIGBEE
    environment:
      - DECONZ_WEB_PORT=88
      - DECONZ_WS_PORT=444
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
```

I can see ConBee in web Interface but at first It seems that It cannot find any light but then I realized that light actually stop flashing after power on, which indicates that they were paired. And If I'm not mistaken I was correct, this is in DB (table devices):
```
id,mac,timestamp,nwk
1,00:21:2e:ff:ff:03:b0:c5,1551287408,0
2,00:15:8d:00:02:4f:38:0d,1551287412,28946
3,00:15:8d:00:02:4f:c8:61,1551287412,18862
4,00:15:8d:00:02:4f:c8:10,1551287412,46193
5,00:15:8d:00:02:4f:a9:5f,1551287458,3335
```
First one is in my opinion ConBee and then I have 4 lights that were powered on during searching process. But lights do not show in GUI.

What should I try to resolve this issue?

Edit:
Firmware version on ConBee is 262f0500 as I had some unexpected errors with latest release in HA, so I did downgrade.
