### ISSUE TITLE
For Consideration: Add support to replace "libde_rest_plugin.so" with custom binary.

### ISSUE THREAD

**Issue by ericvandamme** [marthoc/docker-deconz#114]
It would be a nice to have feature to be able to replace the "libde_rest_plugin.so" plugin with one custom built between releases. I am working with some other people deploying their Home Assistant, but occasionally support for new sensors / lights need to be added.

**Comment by marthoc** [comment]
I think you should be able to do this already, just mount your custom compiled libde_rest_plugin.so into the container:
-v /path/to/your/libde_rest_plugin.so:/usr/share/deCONZ/plugins/libde_rest_plugin.so

**Comment by Krocko** [comment]
If i specify the path to the rest plugin, the custom path for the persist storage (-v /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ \) don't work anymore. Or is ignored.

**Comment by Krocko** [comment]
@marthoc any help on this please?

**Comment by Krocko** [comment]
Anyone got this working?
Would be really good to have this feature.

**Comment by SAOPP** [comment]
I'm also started to compile latest commits before next release, 'coz I want to pair my brand new opple switches... and also confused faced with some procedure to replace plugin library. Not sure where need to move.

**Comment by MarcProe** [comment]
After compiling, I tried to:
```
docker cp ../libde_rest_plugin.so docker:/tmp
sudo docker exec -it deconz bash
cp /tmp/libde_rest_plugin.so /usr/share/deCONZ/plugins
```

After restarting the container, the plugin is simply ignored: 
```
20:22:30:985 HTTP Server listen on address 0.0.0.0, port: 80, root: /usr/share/deCONZ/webapp/
20:22:31:008 CTRL. 3.16.220:22:31:340 dev /dev/ttyAMA0
20:22:31:340 ZCLDB init file /root/.local/share/dresden-elektronik/deCONZ/zcldb.txt
20:22:31:436 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
20:22:31:453 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
20:22:31:727 dev /dev/ttyAMA0
```

**Comment by lukicsl** [comment]
This is strange I forked the git project which creates the docker container (marthoc/deconz) and adapted the Dockerfile

```
.......
COPY libde_rest_plugin.so /usr/share/deCONZ/plugins

VOLUME [ "/root/.local/share/dresden-elektronik/deCONZ" ]

EXPOSE ${DECONZ_WEB_PORT} ${DECONZ_WS_PORT} ${DECONZ_VNC_PORT}

ENTRYPOINT [ "/tini", "--", "/start.sh" ]

```
Which gives 0 results the login to RESt and Phoscon does not work

**Comment by lukicsl** [comment]
I do not understand why this does not work. I created a Dockerfile:
```
FROM marthoc/deconz
COPY libde_rest_plugin.so /usr/share/deCONZ/plugins

```
I verified that the file is copied to the container. Still does nor work. I am not able to login to Phoscon with the credential I used before.

**Comment by SAOPP** [comment]
Well guys, I previously reported that I did not succeed with replacing the plugin with a newly compiled one. Damn it, I'm tired of waiting, I have 6 switches already :))))

**Comment by Rick-Jongbloed** [comment]
For the people using docker on a Raspberry Pi, i managed to compile the plugin from master on the docker image:

Start a shell in the docker image, then run
```
cd /opt
apt update
apt install qt5-default libqt5sql5 libqt5websockets5-dev libqt5serialport5-dev libsqlite3-dev build-essential git
git clone https://github.com/dresden-elektronik/deconz-rest-plugin.git
wget http://deconz.dresden-elektronik.de/ubuntu/beta/deconz-dev-2.05.75.deb
dpkg -x deconz-dev-2.05.75.deb ./deconz-dev
cp ./deconz-dev/usr/include/* /usr/include/ -R
qmake && make -j2
```

now the plugin ../libde_rest_plugin.so is created. Extract the plugin from the docker image and mount it to the image using the -v parameter
-v /path/to/your/libde_rest_plugin.so:/usr/share/deCONZ/plugins/libde_rest_plugin.so`
(I got this command from this thread, didn't test it bc i'm using Kubernetes)

After restarting the container the image should be refreshed and the new plugin is working, without any authentication issues to Phoscon, VNC or the API.

**Comment by lukicsl** [comment]
> wget http://deconz.dresden-elektronik.de/ubuntu/beta/deconz-dev-2.05.75.deb
> dpkg -x deconz-dev-2.05.75.deb ./deconz-dev
> cp ./deconz-dev/usr/include/* /usr/include/ -R
> qmake && make -j2

Compilation fails:
```
/usr/bin/ld: cannot find -ldeCONZ
collect2: error: ld returned 1 exit status
Makefile.Release:321: recipe for target '../libde_rest_plugin.so' failed
make[1]: *** [../libde_rest_plugin.so] Error 1
make[1]: Leaving directory '/home/lukics/git.com/deconz-rest-plugin'
Makefile:38: recipe for target 'release' failed
make: *** [release] Error 2
```
Instead you can do (take care about the architecture, which I did not do in the past):
```
wget -O - http://phoscon.de/apt/deconz.pub.key | \
           sudo apt-key add -

sudo sh -c "echo 'deb [arch=armhf] http://phoscon.de/apt/deconz \
            $(lsb_release -cs)-beta main' > \
            /etc/apt/sources.list.d/deconz.list"
sudo apt update
sudo apt install deconz-dev

```
I had an issue before because I did not see in the command above that [arch] has to be set and  I got the wrong package. Now the library is picked up and loaded

**Comment by lukicsl** [comment]
The complete steps I did on my Pi (armhf):
```
cd
mkdir git.com
cd git.com
git clone https://github.com/dresden-elektronik/deconz-rest-plugin.git
cd deconz-rest-plugin
wget -O - http://phoscon.de/apt/deconz.pub.key | \
           sudo apt-key add -

sudo sh -c "echo 'deb [arch=armhf] http://phoscon.de/apt/deconz \
            $(lsb_release -cs)-beta main' > \
            /etc/apt/sources.list.d/deconz.list"
sudo apt update
sudo apt install deconz-dev
qmake && make -j2
```
I am using docker-compose and defined for all my containers a mountpoint at /datavol.
For Phoscon it is:
```
/datavol/deconz/conf 
/datavol/deconz/lib
```
I copied the compiled file to the mountpoint
`cp ../libde_rest_plugin.so /datavol/deconz/lib`

the docker-compose.yml is:
```
version: "2"
services:
  deconz:
    image: marthoc/deconz:latest
    container_name: deconz
    network_mode: host
    restart: always
    volumes:
      - /datavol/deconz/conf:/root/.local/share/dresden-elektronik/deCONZ
      - /datavol/deconz/lib/libde_rest_plugin.so:/usr/share/deCONZ/plugins/libde_rest_plugin.so
    devices:
      - /dev/ttyAMA0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PASSWORD=.guesswhat.
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0

```

**Comment by Guus-H** [comment]
> The complete steps I did on my Pi (armhf):
> 

So for the newbs (like me) on the block, Raspberry Pi 4, that should normally run armhf? I have googled it, but haven't found a straightforward answer..

**Comment by Rick-Jongbloed** [comment]
> Raspberry Pi 4, that should normally run armhf?

Yes

**Comment by Rick-Jongbloed** [comment]
While my solution does work on the docker image maintained by @marthoc, I tried to replicate the correct way to install the deconz headers using the deCONZ apt repo on the Docker image.

I had to install git, wget build-essential and lsb-release first:
`apt update && apt install wget git lsb-release build-essential`
then the instruction posted by @lukicsl can be used.

**Comment by smesguich** [comment]
Hello !
I'm facing the same issue.
I'm running latest deCONZ docker on my Synology DS918+ with Portainer (1.23.2) and Docker 18.09.6 (API: 1.39). I run deCONZ as stack 

```
version: '2'
services:
  app:
    image: marthoc/deconz
    network_mode: host
    restart: always
    ports:
      - 39980:39980
      - 39981:39981
      - 39982:39982
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/deCONZ/config/:/root/.local/share/dresden-elektronik/deCONZ
      #FOR DEV MODE
      - /volume1/docker/deCONZ/lib/libde_rest_plugin_motion.so:/usr/share/deCONZ/plugins/libde_rest_plugin.so
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=18080
      - DECONZ_WS_PORT=18081
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=18082
      - DECONZ_VNC_PASSWORD=HIDDEN
      - DECONZ_UPNP=1
      - DECONZ_DEVICE=/dev/ttyACM0

```

I've compiled a new lib rest and try to mount it but it's not working ... Same logs except the lib is not loaded by the binary
