### ISSUE TITLE
deCONZ + balena + RPi 3 B + RaspBee unstable

### ISSUE THREAD

**Issue by vstirbu** [marthoc/docker-deconz#213]
Running deconz as a balena multi-container application on a Raspberry PI 3 B with RaspBee hat goes into a firmware connect/disconnect loop.

The initialization log:

```
 deconz  [marthoc/deconz] Starting deCONZ...
 deconz  [marthoc/deconz] Current deCONZ version: 2.05.75
 deconz  [marthoc/deconz] Web UI port: 80
 deconz  [marthoc/deconz] Websockets port: 443
 deconz  [marthoc/deconz] VNC Disabled
 deconz  libpng warning: iCCP: known incorrect sRGB profile
 deconz  12:02:53:752 HTTP Server listen on address 0.0.0.0, port: 80, root: /usr/share/deCONZ/webapp/
 deconz  12:02:53:785 CTRL. 3.16.212:02:53:901 dev /dev/ttyAMA0
 deconz  12:02:53:902 ZCLDB init file /root/.local/share/dresden-elektronik/deCONZ/zcldb.txt
 deconz  12:02:54:124 parent process /bin/sh
 deconz  12:02:54:125 gw run mode: normal
 deconz  12:02:54:125 GW sd-card image version file does not exist: /root/.local/share/dresden-elektronik/deCONZ/gw-version
 deconz  12:02:54:127 DB sqlite version 3.16.2
 deconz  12:02:54:130 DB PRAGMA page_count: 30
 deconz  12:02:54:131 DB PRAGMA page_size: 4096
 deconz  12:02:54:131 DB PRAGMA freelist_count: 0
 deconz  12:02:54:131 DB file size 122880 bytes, free pages 0
 deconz  12:02:54:131 DB PRAGMA user_version: 6
 deconz  12:02:54:131 DB cleanup
 deconz  12:02:54:133 DB create temporary views
 deconz  12:02:54:148 don't close database yet, keep open for 900 seconds
 deconz  12:02:54:149 started websocket server at port 443
 deconz  12:02:54:157 GW firmware update not supported on x86 linux headless
 deconz  12:02:54:160 found node plugin: libde_rest_plugin.so - REST API Plugin
 deconz  12:02:54:165 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
 deconz  12:02:54:191 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
```

and here is the section of log that keeps repeating:

```
 deconz  This plugin does not support propagateSizeHints()
 deconz  11:53:15:907 Device firmware version 0x26330500
 deconz  11:53:15:918 unlocked max nodes: 200
 deconz  11:53:16:015 Device protocol version: 0x010B
 deconz  11:53:16:084 Current channel 15
 deconz  11:53:16:105 CTRL ANT_CTRL 0x03
 deconz  11:53:16:150 Device protocol version: 0x010B
 deconz  11:53:16:224 Current channel 15
 deconz  11:53:16:246 CTRL ANT_CTRL 0x03
 deconz  11:53:27:319 device state timeout ignored in state 3
 deconz  11:53:28:295 device state timeout ignored in state 3
 deconz  11:53:29:295 device state timeout ignored in state 3
 deconz  11:53:30:295 device state timeout ignored in state 3
 deconz  11:53:31:295 device state timeout ignored in state 3
 deconz  11:53:33:295 device state timeout (handled)
 deconz  11:53:33:295 0x0017880106132FC3 error APSDE-DATA.confirm: 0xAE on task
 deconz  11:53:33:301 device disconnected reason: 1, index: 0
 deconz  This plugin does not support propagateSizeHints()
 deconz  11:53:33:795 wait reconnect 15 seconds
 deconz  11:53:33:796 void zmMaster::handleStateIdle(zmMaster::MasterEvent) not connected goto OFF state
 deconz  11:53:33:796 device state timeout ignored in state 1
 deconz  11:53:34:795 wait reconnect 14 seconds
 deconz  11:53:35:795 wait reconnect 13 seconds
 deconz  11:53:36:795 wait reconnect 12 seconds
 deconz  11:53:37:795 wait reconnect 11 seconds
 deconz  11:53:38:796 wait reconnect 10 seconds
 deconz  11:53:39:795 wait reconnect 9 seconds
 deconz  11:53:40:796 wait reconnect 8 seconds
 deconz  11:53:41:795 wait reconnect 7 seconds
 deconz  11:53:42:795 wait reconnect 6 seconds
 deconz  11:53:43:795 wait reconnect 5 seconds
 deconz  11:53:44:795 wait reconnect 4 seconds
 deconz  11:53:45:795 wait reconnect 3 seconds
 deconz  11:53:46:795 wait reconnect 2 seconds
 deconz  11:53:47:795 wait reconnect 1 seconds
```

The balena compose:

```
version: "2.1"

volumes:
  deconz-data:

services:
  deconz:
    image: marthoc/deconz
    network_mode: host
    restart: always
    volumes:
      - "deconz-data:/root/.local/share/dresden-elektronik/deCONZ"
    devices:
      - /dev/ttyAMA0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
```

The image is configured correctly with the overlay `pi3-miniuart-bt`.

Running deconz [natively](https://phoscon.de/en/raspbee/sdcard) with the same hardware setup works without this problems.

**Comment by marthoc** [comment]
What is a “balena multi-container application“? May be unsupported at the moment.

**Comment by peteretep** [comment]
@vstirbu did you ever figure this out? I am experiencing the same issue.

**Comment by vstirbu** [comment]
@peteretep Nope, I haven't pursued this course of action after this issue was closed so swiftly.

In the end I continued with one of the images build by [Phoscon](https://phoscon.de/en/raspbee/sdcard)

**Comment by peteretep** [comment]
Thanks @vstirbu

**Comment by peteretep** [comment]
You need to run the container in privileged mode - https://www.balena.io/docs/learn/develop/hardware/

This worked for me, I did not change the overlay.
```
   deconz:
        image: marthoc/deconz
        restart: always
        privileged: true
        volumes:
            - deconz:/root/.local/share/dresden-elektronik/deCONZ
        ports:
            - "8080:8080"
        devices:
            - /dev/ttyS0:/dev/ttyS0
        environment:
            - DECONZ_DEVICE=/dev/ttyS0
            - DECONZ_WEB_PORT=8080
            - DECONZ_WS_PORT=443
            - DEBUG_INFO=1
            - DEBUG_APS=0
            - DEBUG_ZCL=0
            - DEBUG_ZDP=0
            - DEBUG_OTAU=0
```
