### ISSUE TITLE
DECONZ_DEVICE variable does not seem to be working

### ISSUE THREAD

**Issue by DIYtechie** [marthoc/docker-deconz#222]
For technical reasons, I need to use an environment variable to set devices. However, the DECONZ_DEVICE variable does not seem to be working. 

As an example, the following docker-compose text using `devices: /dev/ttyACM0` creates a container that **works** with ConBee II:
```
   deconz:
    image: marthoc/deconz
    container_name: deconz
    restart: unless-stopped
    network_mode: bridge
    ports:
      - '8090:80'
      - '443:443'
      - '5901:5900'
    volumes:
       - ./volumes/deconz/:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PASSWORD=changeme
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
```

Whereas, the following docker-compose text using `DECONZ_DEVICE=/dev/ttyACM0` creates a container that **will not detect** the ConBee II:

```
   deconz:
    image: marthoc/deconz
    container_name: deconz
    restart: unless-stopped
    network_mode: bridge
    ports:
      - '8090:80'
      - '443:443'
      - '5901:5900'
    volumes:
       - ./volumes/deconz/:/root/.local/share/dresden-elektronik/deCONZ
    environment:
      - DECONZ_DEVICE=/dev/ttyACM0
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PASSWORD=changeme
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
```
