### ISSUE TITLE
Permament Data not stored in /opt/deconz, after recreation of container and volume prune all data lost.

### ISSUE THREAD

**Issue by Springjunky** [marthoc/docker-deconz#239]
the data of the Phoscon-App ist _not_ stored in /opt/deconz it es stored in /root/.local/share/dresden-elektronik/deCONZ

The mapping with docker-compose 
```
   volumes:
      - /etc/localtime:/etc/localtime:ro 
      - /opt/deconz:/mnt/externalSSD/DockerVolumes/DeCONZ/opt/deconz
      - /root/.local/share/dresden-elektronik/deCONZ:/mnt/externalSSD/DockerVolumes/DeCONZ/root/.local/share/dresden-elektronik/deCONZ
 ```
does NOT work, the directory /mnt/externalSSD/DockerVolumes/DeCONZ/opt/deconz is ALWAYS empty and
/root/.local/share/dresden-elektronik/deCONZ:/ ist not propageted ..

With this configruration above docker inspect shows the following.
```
       "Mounts": [
            {
                "Type": "bind",
                "Source": "/root/.local/share/dresden-elektronik/deCONZ",
                "Destination": "/mnt/externalSSD/DockerVolumes/DeCONZ/root/.local/share/dresden-elektronik/deCONZ",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "0e74885b41f5a91f54f22320fe4985c4dd261dd012e20f0c9fe69ac6d99b7ed4",
                "Source": "/var/lib/docker/volumes/0e74885b41f5a91f54f22320fe4985c4dd261dd012e20f0c9fe69ac6d99b7ed4/_data",
                "Destination": "/root/.local/share/dresden-elektronik/deCONZ",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/opt/deconz",
                "Destination": "/mnt/externalSSD/DockerVolumes/DeCONZ/opt/deconz",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/etc/localtime",
                "Destination": "/etc/localtime",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
  ```
After a recreation and docker volume prune all configrutation data is lost

Here is my complete docker-compose 
```
version: "2"
services:
  deconz:
    image: marthoc/deconz
    container_name: Deconz
    network_mode: host
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro 
      - /opt/deconz:/mnt/externalSSD/DockerVolumes/DeCONZ/opt/deconz
      - /root/.local/share/dresden-elektronik/deCONZ:/mnt/externalSSD/DockerVolumes/DeCONZ/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyACM0  
    environment:
      - TZ=Europe/Berlin     
      - DECONZ_VNC_MODE=1
      - DECONZ_WEB_PORT=8000
      - DECONZ_WS_PORT=443
      - DECONZ_VNC_PORT=5901
      - DECONZ_VNC_PASSWORD=changeme
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=1
      - DEBUG_ZDP=1
      - DEBUG_OTAU=1

```
