### ISSUE TITLE
Pi4 & RaspBee 2: Can't connect light or accessories to deCONZ Docker

### ISSUE THREAD

**Issue by mr-bluescreen** [marthoc/docker-deconz#247]
Hi,

I've switched from an Raspberry Pi 3 B+ to the new Raspberry Pi 4 with 8 GB of RAM and am now trying to migrate my deCONZ Setup to the new Pi.

I'm using the RaspBee II on latest Rasbian.

I followed every step from the Docker installation guide and can connect to the deCONZ Web UI but can't connect any devices, light or accessories via ZigBee. Nothing is found :-(
Configuring the RaspBee module on the old 3B+ without docker and everything is working as expected (added Hue Light, Aqara Sensor and Hue Dimmer Switch with no problem)

The RTC is running fine:
```shell
hwclock from util-linux 2.33.1
System Time: 1596325793.077762
Trying to open: /dev/rtc0
Using the rtc interface to the clock.
Last drift adjustment done at 1596197280 seconds after 1969
Last calibration done at 1596197280 seconds after 1969
Hardware clock is on UTC time
Assuming hardware clock is kept in UTC time.
Waiting for clock tick...
ioctl(3, RTC_UIE_ON, 0): Invalid argument
Waiting in loop for time from /dev/rtc0 to change
...got clock tick
Time read from Hardware Clock: 2020/08/01 23:49:55
Hw clock time : 2020/08/01 23:49:55 = 1596325795 seconds since 1969
Time since last adjustment is 128515 seconds
Calculated Hardware Clock drift is 0.000000 seconds
2020-08-02 01:49:54.069732+02:00
```

Here are some details from the WebUI:

```
Produkt: RaspBee
Version: 2.05.79 / 22.5.2020
Firmware: 26610700
ZigBee Kanal: 15
Netzwerk ID: CA03
```

And this is my docker-compose.yml:

```yaml
version: '2'

services:
  deconz:
    image: marthoc/deconz
    container_name: deconz
    network_mode: host
    devices:
      - /dev/ttyAMA0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - TZ=Europe/Berlin
    volumes:
      - /mnt/usb/docker_compose_data/deCONZ:/root/.local/share/dresden-elektronik/deCONZ
    restart: always
```

Thank you for your help, I hope somone could help me!
