### ISSUE TITLE
Trying to setup container yields immeadiate stop with exit-code 139 (segmentation fault) on armv6l

### ISSUE THREAD

**Issue by ChaosNicro** [marthoc/docker-deconz#250]
Hey, I used to run Deconz directly on Raspian and now wanted to try the image. 
Trying to start the container immediately crashes it with exit-code 139. No logs were generated and I recreated the container and repulled the image a few times to rule out random data corruption.

Processor: armv6l (Rpi Zero W)
device: Conbee 2 (ttyACM0)
docker version: 19.03.12
docker-compose:

```
deconz:
    image: marthoc/deconz
    container_name: deconz
    network_mode: host
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - deconz_data:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DECONZ_DEVICE=/dev/ttyACM0
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
```
