### ISSUE TITLE
Bug in September Update: deCONZ 2.05.81, 2.05.83, 2.05.84 not working!

### ISSUE THREAD

**Issue by etique57** [marthoc/docker-deconz#271]
Hello,

I'm a happy user of this docker for a long time now :) but tonight the september update suddenly broke my setup (armhf image, on a tinkerboard S, automatically pulled by watchtower).

Essentially, what I observed:
- container not reachable at all with VNC_MODE=1
- time reported by phoscon was jumping from 1925 to 1935 to 1970, etc.
- had to force the DECONZ_DEVICE environment (--device alone wasn't sufficient) for Phoscon to find it
- Gateway didn't connect to the firmware

I went back to the armhf-2.05.82 image to be able to retrieve control of my system.
Here's a screenshot of the gateway when it's running:
![image](https://user-images.githubusercontent.com/24211083/94743190-45aeb080-0377-11eb-88bf-c89a94359b03.png)

I'd be happy to help debug!

Cheers

**Comment by marthoc** [comment]
There are two potential points of failure: the update to 2.05.83 and the UDEV support. Can you try creating the new container and setting the environment variable UDEV=1?

**Comment by philipproplesch** [comment]
Same situation here with a Raspberry Pi 4. Enabling UDEV fixed it!

**Comment by marthoc** [comment]
@philipproplesch Thanks for testing! The fix might be as simple as changing the default. Everything else seems to work? VNC?

**Comment by philipproplesch** [comment]
@marthoc Not sure about VNC. Phoscon and the REST API seem to be working fine though.

**Comment by etique57** [comment]
I did the following test, with :latest
- with UDEV=on and VNC_MODE=1: no can do, cannot access phoscon app
- with UDEV=on and VNC_MODE=0: like before, phoscon is reachable but cannot access the Conbee

Reverted back to armhf-2.05.82, everything back to normal.

I didn't switch the container to privileged though, should I?

**Comment by bennyzen** [comment]
I had to switch into privileged mode to get it back working. UDEV environment variable alone was not enough.

**Comment by clutwo** [comment]
Same here.. had to revert to armhf-2.05.82 for the system to work again. 
UDEV=1 didn't fix it.

**Comment by phdelodder** [comment]
Adding "privileged: true" in docker compose, does the trick.

**Comment by etique57** [comment]
I confirm, switching to privileged mode solves everything with UDEV=on

**Comment by DOliana** [comment]
I have the same issue. UDEV=1 does not fix it - I did not try privileged mode, since I would like to not run the container in privileged mode for the same reason I do not work as root. What else could we do?

**Comment by marthoc** [comment]
I am likely going to revert the UDEV change for now and investigate further why this is happening.  Until I can do that, please either use the 2.05.82 image or run UDEV=1 and privileged mode.

**Comment by user897943** [comment]
I added --privileged -e UDEV=1 to my docker create command and it now works. Phew! I thought I was going to have to bind each and every one of my 42 lights, 3 fans, and various zigbee buttons I setup for automations.

**Comment by mtressl** [comment]
> --privileged -e UDEV=1 

How would I add this to my docker-compose.xml - looking for an example.

**Comment by phdelodder** [comment]
> > --privileged -e UDEV=1
> 
> How would I add this to my docker-compose.xml - looking for an example.

Example:
```
deconz:
    image: marthoc/deconz:armhf-2.05.83
    container_name: deconz
    network_mode: host
    restart: always
    volumes:
      - deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyUSB0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DECONZ_DEVICE=0
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_DISPLAY=0
      - DECONZ_VNC_PASSWORD=changeme
      - DECONZ_VNC_PORT=5900
      - UDEV=1
      - TZ=Europe/Brussels
    privileged: true
```

**Comment by mtressl** [comment]
Thanks @phdelodder 
Will try (again), changed my docker-compose.xml like this last night but somehow failed.

**Comment by mtressl** [comment]
With `UDEV=1` and `privileged: true` it works for me.

> Thanks @phdelodder
> Will try (again), changed my docker-compose.xml like this last night but somehow failed.

**Comment by S474N** [comment]
> With `UDEV=1` and `privileged: true` it works for me.
> 
> 
> 
> > Thanks @phdelodder
> 
> > Will try (again), changed my docker-compose.xml like this last night but somehow failed.

Also for me solved the problem.

**Comment by Jimmy-SafeCash** [comment]
Surely adding privileged: true cannot be classed as a fix for security reasons? Has something changed that now requires this flag or is it a bug with .83 as it's still in beta?

**Comment by marthoc** [comment]
@Jimmy-SafeCash its a workaround until I can properly fix.

**Comment by Jimmy-SafeCash** [comment]
> @Jimmy-SafeCash its a workaround until I can properly fix.

Great, thanks for confirming @marthoc. Look forward to this release as it will hopefully enable me to hook up my new sonoff sensors.

**Comment by arthurspa** [comment]
Wow, I spent hours trying to find out the problem why my ConbeeII was not showing. After I added privileged: true and UDEBE=1 it worked.

Thank you for the workaround.

**Comment by Jimmy-SafeCash** [comment]
Latest 2.05.84 not working either. Appears to show the same symptoms - not sure if you have had a chance to address the existing bug and whether this is same problem.

**Comment by crixyd** [comment]
Same issue here on 2.05.84 (latest)... deCONZ is 100% unusable, with all of the same issues reported above on 2.05.83

Using RPi 4 / RaspBee II / Docker (compose)

**Comment by S474N** [comment]
@crixyd why 100% unusable? You can do the workaround fix and wait for final solution.

**Comment by marthoc** [comment]
If a brave soul could test my fixes, I have pushed them to the branch `october-bugfix`. You will need to build the image locally before testing as follows (I will try to push updated images to GitHub for testing purposes, but in the meantime):
```
git checkout https://github.com/marthoc/docker-deconz
cd docker-deconz
git checkout october-bugfix
docker build -t marthoc/deconz:test --build-arg VERSION=2.05.84 --build-arg CHANNEL=stable ./[arch]
```
Be sure to replace [arch] with your arch (amd64, arm64, or armv7). After the image is built, please use your normal run command (i.e. no UDEV=1, no --privileged, use VNC if you wish) and report the results! Thanks in advance.

**Comment by marthoc** [comment]
Test images now available for version 2.05.84 incorporating the bug fixes. Please test! Tags are amd64-test, arm64-test, and armv7-test.

**Comment by Jimmy-SafeCash** [comment]
> Test images now available for version 2.05.84 incorporating the bug fixes. Please test! Tags are amd64-test, arm64-test, and armv7-test. Appears to now work correctly in my limited testing on amd64 only this evening.

Thanks @marthoc for pushing the fix. I'll endeavor to test this evening.

**Comment by corneyl** [comment]
I have the same problems as described above with 2.05.84, and are now running 2.05.79.
I've tested the `armv7-test` image, but the Phoscon web-interface is not reachable and I get the following logging:
```
[marthoc/deconz] Starting deCONZ...
[marthoc/deconz] Current deCONZ version: 2.05.84
[marthoc/deconz] Web UI port: 8080
[marthoc/deconz] Websockets port: 8443
[marthoc/deconz] VNC Disabled
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QStandardPaths: wrong ownership on runtime directory /tmp/runtime-root, -2 instead of 0
libpng warning: iCCP: known incorrect sRGB profile
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
```

**Comment by marthoc** [comment]
@corneyl Not sure whether these issues are related but can you share the docker run line you are using to create the container?

**Comment by etique57** [comment]
Hello @marthoc 

Hummm unfortunately the october update broke my set-up again. I had to go back to image 2.0.5.81 (14 sept).

What is the recommended configuration now? UDEV, priviledged, etc? Shall I open a new issue?

Thanks!

**Comment by marthoc** [comment]
@etique57 yes please open a new issue and report the details. UDEV no longer applies and should not require privileged mode.

**Comment by DOliana** [comment]
@marthoc for me the armv7-test image is working properly on a RPi 4 (no privileged mode, UDEV variable not set, so probably deactivated). I have not turned on VNC.

Where will you notify that testing is done and a new fixed version is available?

**Comment by marthoc** [comment]
@DOliana Thanks for confirming. New versions are already built including the fixes for both stable (2.05.84) and beta (2.05.85).

**Comment by corneyl** [comment]
@marthoc I started it with `docker-compose` with this config:
```
deconz:
  image: marthoc/deconz:armv7-test
  ports:
    - 8080:8080
  networks:
    - ha-net
  restart: always
  volumes:
    - ./data/deconz:/root/.local/share/dresden-elektronik/deCONZ
    - ./data/zigbee-otau-fw:/root/otau
  devices:
    - /dev/ttyAMA0
  environment:
    - DECONZ_WEB_PORT=8080
    - DECONZ_WS_PORT=8443
    - DEBUG_INFO=1
    - DEBUG_APS=0
    - DEBUG_ZCL=0
    - DEBUG_ZDP=0
    - DEBUG_OTAU=0
```
Docker doesn't run as root indeed.
