### ISSUE TITLE
Completely wrong and random time and date in Phoscon App every few seconds

### ISSUE THREAD

**Issue by LANtastic** [marthoc/docker-deconz#276]
Tried to install the docker image as described in the instructions via docker-compose and using the command line version.
docker-compose.yml file:

```
version: '3'
services:
  deconz:

    image: marthoc/deconz
    container_name: deconz
    restart: always
    ports:
      - "80:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ~/.local/share/dresden-elektronik/deCONZ:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=80
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - TZ=Europe/Berlin
    networks:
      MacVlan100:
        ipv4_address: 10.0.100.30
 networks:
  MacVlan100:
    external: true
```

Everything is fine, the container is created as expected and reachable.
However ... in the menu Gateway > Advanced the app always shows a totally wrong time, as well as a wrong date. 

The shown date and time is completely random and changes every few seconds to another totally random date!
These dates vary from any date and time starting 1971. At least I did not see any earlier dates. 

I ran `docker exec -it deconz date` 3 times in a row within 5 seconds and this is what I get: 

```
user@Pi4:~/deconz $ docker exec -it deconz date
Thu Dec 10 02:43:09 CET 1970
failed to resize tty, using default size
user@Pi4:~/deconz $ docker exec -it deconz date
Sun Jan 17 02:04:45 CET 1971
failed to resize tty, using default size
user@Pi4:~/deconz $ docker exec -it deconz date
Mon Feb 22 08:28:45 CET 1971
failed to resize tty, using default size
user@Pi4:~/deconz $
```

My Setting: 
Raspberry Pi 4, 4GByte, ConBee II stick.
Using latest version of docker and all available updates of Pi OS.
All other containers, are using the correct time and date.

Installing the deconz software directly on my PI works perfectly. 
using date command on the host, returns the correct time and date,

Any ideas?
