### ISSUE TITLE
'XDG_RUNTIME_DIR not set' error in deCONZ version 2.05.84

### ISSUE THREAD

**Issue by corneyl** [marthoc/docker-deconz#297]
I get the following error when updating from 2.05.79 to the newest stable version of deCONZ:
```
[marthoc/deconz] Starting deCONZ...
[marthoc/deconz] Current deCONZ version: 2.05.84
[marthoc/deconz] Web UI port: 8080
[marthoc/deconz] Websockets port: 8443
[marthoc/deconz] VNC Disabled
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QStandardPaths: wrong ownership on runtime directory /tmp/runtime-root, -2 instead of 0
libpng warning: iCCP: known incorrect sRGB profile
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
```

When I set a value for `XDG_RUNTIME_DIR`, e.g. `XDG_RUNTIME_DIR=/root/xdg`, I get the following:
```
[marthoc/deconz] Starting deCONZ...
[marthoc/deconz] Current deCONZ version: 2.05.84
[marthoc/deconz] Web UI port: 8080
[marthoc/deconz] Websockets port: 8443
[marthoc/deconz] VNC Disabled
QCoreApplication::arguments: Please instantiate the QApplication object first
QStandardPaths: XDG_RUNTIME_DIR points to '/root/xdg' which is not a directory
libpng warning: iCCP: known incorrect sRGB profile
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
```

Container gets started using `docker-compose`:
```
deconz:
  image: marthoc/deconz:armhf-2.05.84
  ports:
    - 8080:8080
  networks:
    - ha-net
  restart: always
  volumes:
    - ./data/deconz:/root/.local/share/dresden-elektronik/deCONZ
    - ./data/zigbee-otau-fw:/root/otau
  devices:
    - /dev/ttyAMA0
  environment:
    - DECONZ_WEB_PORT=8080
    - DECONZ_WS_PORT=8443
    - DEBUG_INFO=1
    - DEBUG_APS=0
    - DEBUG_ZCL=0
    - DEBUG_ZDP=0
    - DEBUG_OTAU=1
```

It seems related to Qt and is probably related to #295, can you confirm this @Kane610?
