### ISSUE TITLE
VNC stopped working when updating to 2.05.88

### ISSUE THREAD

**Issue by Burningstone91** [marthoc/docker-deconz#310]
I updated to the latest version today and VNC stopped working for me. I get the following errors in the logs:

```log
Password:[marthoc/deconz] Starting deCONZ...
[marthoc/deconz] Current deCONZ version: 2.05.88
[marthoc/deconz] Web UI port: 8080
[marthoc/deconz] Websockets port: 443
[marthoc/deconz] VNC port: 5900
Fatal error: glibc detected an invalid stdio handle
Aborted (core dumped)

You will require a password to access your desktops.

getpassword error: Inappropriate ioctl for device
qt.qpa.screen: QXcbConnection: Could not connect to display :0
Could not connect to any X display.
```
Relevant part from docker-compose:

```yaml
  deconz:
    container_name: deconz
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=8080
      - DECONZ_WS_PORT=443
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=5900
      - DECONZ_VNC_PASSWORD=********
      - DECONZ_DEVICE=/dev/ttyACM0
#      - UDEV=1
      - TZ=Europe/Zurich
    image: marthoc/deconz:stable
    network_mode: host
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./deconz:/root/.local/share/dresden-elektronik/deCONZ
```
Without VNC disabled it runs fine.
