### ISSUE TITLE
After update of 2.05.86 and higher the use of /dev/serial/by-id/ not possible anymore

### ISSUE THREAD

**Issue by canedje** [marthoc/docker-deconz#317]
After an update to 2.05.86 I had trouble not getting my zigbee/ docker running anymore.
After a long time trouble shooting I did find that using "/dev/serial/by-id/my conbee name" device. Is not possible anymore in usb conbee variable and usb device name: variable.
Only the use of /dev/ttyACM0 is possible.

Thats not a big problem (After finding out :-) ), but I did like the /dev/serial/by-id/ name because this is never changing.
/dev/ttyACM0 can change in time

**Comment by lubbertkramer** [comment]
Can confirm this, just updated with conbee 2 and set the ttyACM0 with id to conbee (just like i did on earlier releases) Below my config, i have now replaced conbee for ttyACM0 and it's working

```
  deconz:
    container_name: deconz
    image: marthoc/deconz:amd64-2.09.00
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=1
      - DECONZ_DEVICE=/dev/ttyACM0
      # - DECONZ_DEVICE=/dev/conbee
      - DECONZ_WEB_PORT=8383
      - DECONZ_WS_PORT=8444
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=5900
      - DECONZ_VNC_PASSWORD=${DECONZVNC}
    network_mode: host
    ports:
      - 8383:8383
    volumes:
      - ${BASE}/deconz:/root/.local/share/dresden-elektronik/deCONZ
      - ${BASE}/deconz/otau:/root/otau
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyACM0
      # - /dev/conbee
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8383"]
      interval: 60s
      timeout: 30s
      retries: 6
    logging:
        options:
            max-size: 10m
```
