### ISSUE TITLE
First command gets dropped after time of no actions

### ISSUE THREAD

**Issue by KarstenSiemer** [marthoc/docker-deconz#330]
Hello currently running stable at 2.07.01 with fw 26660700 with conbee 2 stick on a qnap nas.
I have grouped my lights and control them either via alexa or switches.
Often times the first command by a switch goes ignored or a alexa command gets answered by alexa with 'OK', but nothing happens.
The second try always works and all consecutive commands work like a charm.
But the first command after like 5 minutes of inactivity gets dropped.
I can't see any logs that are indicative of failures.

I am using docker-compose and this is part of my setup:
```
version: "3.3"
services:
  deconz:
    image: marthoc/deconz:stable
    restart: unless-stopped
    container_name: deconz
    mac_address: [DELETED]
    networks:
      qnet-static-bond0-79e6cc:
        ipv4_address: [DELETED]
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - deconz-data:/root/.local/share/dresden-elektronik/deCONZ
    ports:
      - "5900:5900"
      - "80:80"
      - "443:443"
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_DEVICE=/dev/ttyACM0
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - TZ=Europe/Berlin
      - DECONZ_VNC_MODE=0
```

These are the devices in my zigbee net:
![image](https://user-images.githubusercontent.com/40307978/101919382-c76a5800-3bca-11eb-9de2-f6ff39542868.png)
I am directly using phoscon to group and control via switches. For alexa I am using iobroker and node-red.
Node-Red for alexa is configured via node-red-contrib-amazon-echo and looks like this:
![image](https://user-images.githubusercontent.com/40307978/101919830-54adac80-3bcb-11eb-812e-63b845d65d35.png)

But since I also experience the problem with the switches, it should have nothing to do with alexa integration.

Has anyone else this problem or an idea of how I can find the reason for it?
Thanks in advance for help!
