### ISSUE TITLE
Won't start with latest version (2.11)

### ISSUE THREAD

**Issue by LightningRhino** [marthoc/docker-deconz#385]
Tonight my system pulled the latest deconz version (with watchtower).
Now the webgui is not reachable.
Last log entries:

> [marthoc/deconz] Starting deCONZ...
> [marthoc/deconz] Current deCONZ version: 2.11.00
> [marthoc/deconz] Web UI port: 8100
> [marthoc/deconz] Websockets port: 8443
> [marthoc/deconz] VNC port: 5900
> Killing Xtigervnc process ID 23... which was already dead
> Cleaning stale pidfile '/root/.vnc/dockerpi:0.pid'!
> Cleaning stale x11 lock '/tmp/.X0-lock'!
> Cleaning stale x11 lock '/tmp/.X11-unix/X0'!
> 
> New 'dockerpi:0 (root)' desktop at :0 on machine dockerpi
> 
> Starting applications specified in /etc/X11/Xvnc-session
> Log file is /root/.vnc/dockerpi:0.log
> 
> Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /root/.vnc/passwd dockerpi:0 to connect to the VNC server.
> 
> Fatal Python error: pyinit_main: can't initialize time
> Python runtime state: core initialized
> PermissionError: [Errno 1] Operation not permitted
> 
> Current thread 0xb6fe4460 (most recent call first):
> <no Python frame>
> [marthoc/deconz] NOVNC port: 6080

After going back to previous version 2.11.00 / 14.3.2021 (also 2.11 ?!?) everything is working again (although the system wouldn't want to accept my password and I had to reset it).

**Comment by MrTeal** [comment]
I'm also having issues after this update. First I could not login to the GUI, after a power cycle of the gateway I managed to login, but it says that the Conbee is not connected (firmware not connected, vendor unknown).
Docker logs show this:
```
[marthoc/deconz] Starting deCONZ...
[marthoc/deconz] Current deCONZ version: 2.11.00
[marthoc/deconz] Web UI port: 80
[marthoc/deconz] Websockets port: 443
[marthoc/deconz] VNC Disabled
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
libpng warning: iCCP: known incorrect sRGB profile
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
QWaitCondition::wait(): cv wait failure: Invalid argument
QWaitCondition::wait(): cv wait failure: Invalid argument
```

**Comment by gareth-ellis** [comment]
I have the same - it seems like the release notes expect novnc to be disabled....but for me because the DECONZ_NOVNC_PORT variable wasnt set, it tried to enable it anyway.

I set to 0, but now mine hangs at a similar place to yours. I tried logging in and rerunning start.sh with bash -x but then it core dumped and the container restarted

**Comment by MrTeal** [comment]
Reverted to stable release for now (I cleaned up all my old images to create some disk space minutes before realising Deconz was broken..)
Luckily that works and I can turn on my lights again 😁

**Comment by BorussiaPlayer17** [comment]
Same here. Latest docker image is broken. As @MrTeal did, I switched to stable for now.

**Comment by phdelodder** [comment]
@LightningRhino Can you provide your compose file or the start up command?

**Comment by phdelodder** [comment]
I can't reproduce the error on a AMD64, what I'm image are you using?

**Comment by BorussiaPlayer17** [comment]
Runs on armv7. Raspberry Pi 3B.

**Comment by MrTeal** [comment]
@phdelodder i had it on this image on raspberry pi 4:
REPOSITORY                     TAG              IMAGE ID       CREATED        SIZE
marthoc/deconz                 latest           15e3bbfe3b5b   10 hours ago   562MB

**Comment by LightningRhino** [comment]
> @LightningRhino Can you provide your compose file or the start up command?

`docker run -d --name mydeconz --net=host --restart=unless-stopped -v dcnz-vol:/root/.local/share/dresden-elektronik/deCONZ -v /home/pi/otau:/root/otau -e TZ=Europe/Berlin -e DECONZ_WEB_PORT=8100 -e DECONZ_WS_PORT=8443 -e DECONZ_VNC_MODE=1 -e DECONZ_VNC_PASSWORD=foobar --device=/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE1962626-if00:/dev/ttyACM0 --dns=192.168.178.222 marthoc/deconz`

**Comment by phdelodder** [comment]
So I several errors, can some one please provide me with a the log file found on /root/.vnc/ ?

**Comment by phdelodder** [comment]
```
Fatal Python error: pyinit_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted
```
@LightningRhino Seems to be an permission error, could it be possible to recreate the container? 

@gareth-ellis is this the dump: https://github.com/marthoc/docker-deconz/issues/386?

**Comment by gareth-ellis** [comment]
@phdelodder  looks like it - I wasnt sure if it was due to be manually starting after. Need anything more for that? ive siwtch back to stable but can flip back again and get some info if it helps

**Comment by LightningRhino** [comment]
> 
> @LightningRhino Seems to be an permission error, could it be possible to recreate the container?
> 

I recreated the container by going back to the previous version. Or do I get you wrong?

**Comment by phdelodder** [comment]
@MrTeal the reason is that you are running an out of date libseccomp2, you can either use privileged to get it working or upgrade the library. More info: https://askubuntu.com/questions/1263284/apt-update-throws-signature-error-in-ubuntu-20-04-container-on-arm

With the privileged, the conbee stick connects.

**Comment by phdelodder** [comment]
@LightningRhino Each time you change version the container is recreated. 

- stop the container
- remove the container but not you volume(s)
- execute the docker run command

let me know if that's possible. I have received comfirmation that it's running on a RPI 3B using:

```
  deconz:
    image: marthoc/deconz:armhf-2.11.00
    #build:
    #  context: ./docker-deconz/armv7
    container_name: deconz
    network_mode: host
    restart: always
    volumes:
      - /home/lodder/docker/config/deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyUSB0
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DECONZ_DEVICE=0
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_DISPLAY=0
      - DECONZ_VNC_PASSWORD=changeme
      - DECONZ_VNC_PORT=5900
      - TZ=Europe/Brussels
      - DECONZ_DEVICE=/dev/ttyUSB0
    privileged: true
```
