### ISSUE TITLE
Segmentation fault on deconz docker

### ISSUE THREAD

**Issue by bouyssic** [marthoc/docker-deconz#397]
Hello team,

I need your help as I keep having segmentation faults on my deconz docker. I can't understand why as it was working great yesterday. 

I was able to have it start without any issues by restarting the HOST, but I would like to understand what happened if at all possible. 

Here is my docker compose: 
```
  deconz:
    image: marthoc/deconz:stable
    container_name: deconz
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./config/deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
#      - /dev/ttyACM1:/dev/ttyACM1
      - /dev/ttyACM1
    environment:
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=4443
      - DEBUG_INFO=2
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DECONZ_DEVICE=/dev/ttyACM1
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=5900
      - TZ=Europe/Paris
```

Here are the logs from start of the docker till it fails:
[deconz_logs.txt](https://github.com/marthoc/docker-deconz/files/6491940/deconz_logs.txt)

Sorry if I posted in the wrong section, let me know if I have to move this. 
Regards
Christian
