### ISSUE TITLE
unable to login when NGINX is in front of phoscon to provide HTTPS encryption

### ISSUE THREAD

**Issue by anubisg1** [marthoc/docker-deconz#399]
as described.

If i access phoscon via HTTP on the DECONZ_WEB_PORT i can login no problem but if i place phoscon behind NGINX Reverse Proxy in order to provide SSL i can no longer login .

i can see that when i press the login button i get error 403 for the "/api" call and this error is returned:

[{"error":{"address":"/","description":"link button not pressed","type":101}}]

docker compose is the following:

```
version: '3.4'
services:
  deconz:
    image: marthoc/deconz:stable
    container_name: deconz
    restart: always
    network_mode: host
    volumes:
      - /volume1/docker/deconz/deCONZ:/root/.local/share/dresden-elektronik/deCONZ
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=4080
      - DECONZ_WS_PORT=4443
      - DECONZ_VNC_PORT=5900
      - DECONZ_NOVNC_PORT=6080
      - DECONZ_DEVICE=/dev/ttyACM0
      - DECONZ_VNC_PASSWORD=changemehere
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
```
