### ISSUE TITLE
Deconz is not reachable from defined port

### ISSUE THREAD

**Issue by LeducH** [marthoc/docker-deconz#406]
I want to run deconz in a container. 

my docker compose file has the following content 

```
version: '3.3'
services:
    deconz:
        image: marthoc/deconz
        container_name: deconz
        network_mode: host
        restart: always
        volumes:
            - '/mnt/shared/AppData/deconz:/root/.local/share/dresden-elektronik/deCONZ'
        devices:
            - /dev/ttyACM0
        environment:
            - DECONZ_WEB_PORT=8085
            - DECONZ_WS_PORT=8443
```

but when I deploy it with `docker-compose up` I am unable to reach it at 
`192.168.1.201:8085` or `192.168.1.201:8443`. are there any configuration I need to take. 

```
% docker-compose up  
Starting deconz ... done
Attaching to deconz
deconz    | [marthoc/deconz] Starting deCONZ...
deconz    | [marthoc/deconz] Current deCONZ version: 2.12.01
deconz    | [marthoc/deconz] Web UI port: 8085
deconz    | [marthoc/deconz] Websockets port: 8443
deconz    | [marthoc/deconz] VNC Disabled
deconz    | QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
deconz    | libpng warning: iCCP: known incorrect sRGB profile
deconz    | This plugin does not support propagateSizeHints()
deconz    | This plugin does not support propagateSizeHints()
deconz    | 08:55:41:945 HTTP Server listen on address 0.0.0.0, port: 8085, root: /usr/share/deCONZ/webapp/
deconz    | 08:55:42:094 ZCLDB init file /root/.local/share/dresden-elektronik/deCONZ/zcldb.txt
deconz    | 08:55:42:171 parent process /bin/sh
deconz    | 08:55:42:171 gw run mode: normal
deconz    | 08:55:42:171 GW sd-card image version file does not exist: /root/.local/share/dresden-elektronik/deCONZ/gw-version
deconz    | 08:55:42:176 DB sqlite version 3.27.2
deconz    | 08:55:42:177 DB PRAGMA page_count: 33
deconz    | 08:55:42:177 DB PRAGMA page_size: 4096
deconz    | 08:55:42:177 DB PRAGMA freelist_count: 0
deconz    | 08:55:42:177 DB file size 135168 bytes, free pages 0
deconz    | 08:55:42:177 DB PRAGMA user_version: 7
deconz    | 08:55:42:177 DB cleanup
deconz    | 08:55:42:183 DB create temporary views
deconz    | 08:55:42:230 started websocket server at port 8443
deconz    | 08:55:42:233 [INFO] - Found file containing button maps. Parsing data...
deconz    | 08:55:42:244 [INFO] - Button maps loaded.
deconz    | 08:55:42:247 dlg action: Read binding table
deconz    | 08:55:42:248 found node plugin: libde_rest_plugin.so - REST API Plugin
deconz    | 08:55:42:250 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
deconz    | 08:55:42:260 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
deconz    | 08:55:42:280 LightNode 1: Configuration tool 1 added
deconz    | 08:55:42:365 LightNode 3: Reading light sofa added
deconz    | 08:55:42:368 SensorNode 4 set node 0xbc33acfffebd5abc
deconz    | 08:55:42:370 SensorNode 2 set node 0xbc33acfffebac162
deconz    | 08:55:42:373 LightNode 2: Dinnertable light added
deconz    | This plugin does not support propagateSizeHints()
deconz    | 08:55:45:479 Device firmware version 0x26660700 ConBee II
deconz    | 08:55:45:490 unlocked max nodes: 200
deconz    | 08:55:45:604 Device protocol version: 0x010C
deconz    | 08:55:45:682 Current channel 15
deconz    | 08:55:45:708 CTRL ANT_CTRL 0x03
deconz    | 08:55:45:747 Device protocol version: 0x010C
deconz    | 08:55:45:850 CTRL ANT_CTRL 0x03
deconz    | 08:55:47:230 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26660700.bin.GCF
deconz    | 08:55:47:230 GW firmware version: 0x26660700
deconz    | 08:55:47:231 GW firmware version is up to date: 0x26660700
deconz    | 08:55:47:447 Announced to internet https://phoscon.de/discover
deconz    | 08:55:48:941 New websocket 192.168.178.201:54890 (state: 3) 
deconz    | 08:56:13:267 Bind response success for 0x00158d0003278edc ep: 0x01 cluster: 0x0006
deconz    | 08:56:13:351 ZCL configure reporting rsp seq: 154 0x00158D0003278EDC for ep: 0x01 cluster: 0x0006 attr: 0x0000 status: 0x00
deconz    | 08:56:13:455 Bind response success for 0x00158d0003278edc ep: 0x01 cluster: 0x0008
deconz    | 08:56:13:456 skip configure report for cluster: 0x0008 attr: 0x0000 of node 0x00158D0003278EDC (wait reading or unsupported)
deconz    | 08:56:14:587 Bind response success for 0x00158d0003278edc ep: 0x01 cluster: 0x0300
deconz    | 08:56:14:587 skip configure report for cluster: 0x0300 attr: 0x0003 of node 0x00158D0003278EDC (wait reading or unsupported)
deconz    | 08:56:14:587 skip configure report for cluster: 0x0300 attr: 0x0004 of node 0x00158D0003278EDC (wait reading or unsupported)
deconz    | 08:56:14:664 ZCL configure reporting rsp seq: 156 0x00158D0003278EDC for ep: 0x01 cluster: 0x0300 attr: 0x0008 status: 0xC1
deconz    | 08:56:32:763 Bind response success for 0x00158d0003278edc ep: 0x01 cluster: 0x0006
deconz    | 08:56:32:763 skip configure report for cluster: 0x0006 attr: 0x0000 of node 0x00158D0003278EDC (seems to be active)
deconz    | 08:56:36:786 Bind response success for 0x00158d0003278edc ep: 0x01 cluster: 0x0300
deconz    | 08:56:36:786 skip configure report for cluster: 0x0300 attr: 0x0007 of node 0x00158D0003278EDC (seems to be active)
deconz    | 08:56:36:786 skip configure report for cluster: 0x0300 attr: 0x0003 of node 0x00158D0003278EDC (wait reading or unsupported)
deconz    | 08:56:36:786 skip configure report for cluster: 0x0300 attr: 0x0004 of node 0x00158D0003278EDC (wait reading or unsupported)
deconz    | 08:56:36:786 skip configure report for cluster: 0x0300 attr: 0x0008 of node 0x00158D0003278EDC (seems to be active)
deconz    | 08:56:42:313 Device TTL 6425 s flags: 0x7
deconz    | 08:56:43:202 Skip idle timer callback, too early: elapsed 919 msec


```

**Comment by senilio** [comment]
No hints in the output from the docker-compose up command?

**Comment by LeducH** [comment]
I updated the original post

**Comment by senilio** [comment]
Does netstat -tln show these ports allocated on the docker host?

I'd suggest not running in network_mode: host, but instead network_mode: bridge, and add a ports section in the compose file where you define the ports to be exposed from the container to the host. These should mirror the ports you defined in the environment section.

There's examples of how to do this in the readme of this repo.

**Comment by LeducH** [comment]
Sorry but the readme suggested the `host` option for the the compose file. where is a mention of `bridge`? A text search over the README.md page yields zero results for the term `bridge`. 

but do mean to configure the docker compose file as follows 
```
version: '3.3'
services:
    deconz:
        image: marthoc/deconz
        container_name: deconz
        restart: always
        ports:                 
          - 8085:8085          
          - 8443:8443   
        volumes:
            - '/mnt/shared/AppData/deconz:/root/.local/share/dresden-elektronik/deCONZ'
        devices:
            - /dev/ttyACM0
        environment:
            - DECONZ_WEB_PORT=8085
            - DECONZ_WS_PORT=8443
```

**Comment by senilio** [comment]
There is no mention of `bridge`because `bridge`is the default mode of docker. Defining it is merely for clarity, up to you.

Something like that yes, although the environment variables can be omitted as well, and the port mapping can be handled in the ports section.

```
version: '2'
services:
    deconz:
        image: marthoc/deconz
        container_name: deconz
        restart: always
        ports:                 
          - 80:8085          
          - 443:8443   
        volumes:
            - '/mnt/shared/AppData/deconz:/root/.local/share/dresden-elektronik/deCONZ'
        devices:
            - /dev/ttyACM0
```
