### ISSUE TITLE
Websocket error

### ISSUE THREAD

**Issue by LeducH** [marthoc/docker-deconz#411]
I want to integrate deconz in home assistant. 

But the lights stay on even when I want to switch them off in home assistant. In deconz it work fine. 

I get the error in home assistant 

```
homeassistant    | Restarting Home Assistant
homeassistant    | 2021-07-27 13:06:16 ERROR (MainThread) [pydeconz.websocket] Websocket is not accessible (192.168.178.201)

```

compose 

```
version: '3.3'
services:
    deconz:
        image: marthoc/deconz
        container_name: deconz
        ports:                 
          - 8085:80          
          - 8443:8443   
        restart: always
        volumes:
            - '/mnt/shared/AppData/deconz:/root/.local/share/dresden-elektronik/deCONZ'
        devices:
            - /dev/ttyACM0
        environment:
            - DECONZ_WS_PORT=8443



```

partial logs 

```
deconz    | 11:09:24:232 Set sensor check interval to 100 milliseconds
deconz    | 11:09:25:986 Bind response success for 0xbc33acfffebac162 ep: 0x01 cluster: 0x0001
deconz    | 11:09:28:052 ZCL configure reporting rsp seq: 43 0xBC33ACFFFEBAC162 for ep: 0x01 cluster: 0x0001 attr: 0x0021 status: 0x00
deconz    | 11:09:59:276 Device TTL 5912 s flags: 0x7
deconz    | 11:10:04:233 GW firmware version: 0x26660700
deconz    | 11:10:04:233 GW firmware version is up to date: 0x26660700
deconz    | [marthoc/deconz] Starting deCONZ...
deconz    | [marthoc/deconz] Current deCONZ version: 2.12.03
deconz    | [marthoc/deconz] Web UI port: 80
deconz    | [marthoc/deconz] Websockets port: 443
deconz    | [marthoc/deconz] VNC Disabled
deconz    | QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
deconz    | libpng warning: iCCP: known incorrect sRGB profile
deconz    | This plugin does not support propagateSizeHints()
deconz    | This plugin does not support propagateSizeHints()
deconz    | 11:10:12:917 HTTP Server listen on address 0.0.0.0, port: 80, root: /usr/share/deCONZ/webapp/
deconz    | 11:10:13:087 ZCLDB init file /root/.local/share/dresden-elektronik/deCONZ/zcldb.txt
deconz    | 11:10:13:130 parent process /bin/sh
deconz    | 11:10:13:130 gw run mode: normal
deconz    | 11:10:13:130 GW sd-card image version file does not exist: /root/.local/share/dresden-elektronik/deCONZ/gw-version
deconz    | 11:10:13:130 DB sqlite version 3.27.2
deconz    | 11:10:13:131 DB PRAGMA page_count: 33
deconz    | 11:10:13:131 DB PRAGMA page_size: 4096
deconz    | 11:10:13:131 DB PRAGMA freelist_count: 0
deconz    | 11:10:13:131 DB file size 135168 bytes, free pages 0
deconz    | 11:10:13:131 DB PRAGMA user_version: 7
deconz    | 11:10:13:131 DB cleanup
deconz    | 11:10:13:150 DB create temporary views
deconz    | 11:10:13:170 started websocket server at port 443
deconz    | 11:10:13:171 [INFO] - Found file containing button maps. Parsing data...
deconz    | 11:10:13:182 [INFO] - Button maps loaded.
deconz    | 11:10:13:183 dlg action: Read binding table
deconz    | 11:10:13:183 found node plugin: libde_rest_plugin.so - REST API Plugin
deconz    | 11:10:13:185 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
deconz    | 11:10:13:191 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
deconz    | 11:10:13:211 LightNode 1: Configuration tool 1 added
deconz    | 11:10:13:285 SensorNode 2 set node 0xbc33acfffebac162
deconz    | 11:10:13:290 LightNode 3: Reading light sofa added
deconz    | 11:10:13:294 LightNode 2: Dinnertable light added
deconz    | 11:10:13:295 SensorNode 4 set node 0xbc33acfffebd5abc
deconz    | This plugin does not support propagateSizeHints()
deconz    | 11:10:16:405 Device firmware version 0x26660700 ConBee II
deconz    | 11:10:16:415 unlocked max nodes: 200
deconz    | 11:10:16:529 Device protocol version: 0x010C
deconz    | 11:10:16:606 Current channel 15
deconz    | 11:10:16:632 CTRL ANT_CTRL 0x03
deconz    | 11:10:16:678 Device protocol version: 0x010C
deconz    | 11:10:16:782 CTRL ANT_CTRL 0x03
deconz    | 11:10:18:237 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26660700.bin.GCF
deconz    | 11:10:18:237 GW firmware version: 0x26660700
deconz    | 11:10:18:237 GW firmware version is up to date: 0x26660700
deconz    | 11:10:18:473 Announced to internet https://phoscon.de/discover
deconz    | 11:10:28:078 	0x0017880109036423 force poll (2)
deconz    | 11:10:28:823 	0x0017880109036423 force poll (2)
deconz    | 11:10:30:476 	0x0017880109036423 force poll (2)
```

**Comment by Kane610** [comment]
You can't portmap the websocket port. The home assistant integration gets the websocket port from Deconz so it needs to be configured appropriately.

Use environment variable  -e DECONZ_WS_PORT=8443 in your compose file

**Comment by LeducH** [comment]
same error. 

```
2021-07-27 13:52:07 ERROR (MainThread) [pydeconz.websocket] Websocket is not accessible (192.168.178.201)
```

I changed the compose and restarted all

**Comment by Kane610** [comment]
What does your compose look like now?

**Comment by LeducH** [comment]
I changed it in the description 

```
version: '3.3'
services:
    deconz:
        image: marthoc/deconz
        container_name: deconz
        ports:                 
          - 8085:80          
          - 8443:443   
        restart: always
        volumes:
            - '/mnt/shared/AppData/deconz:/root/.local/share/dresden-elektronik/deCONZ'
        devices:
            - /dev/ttyACM0
        environment:
            - DECONZ_WS_PORT=8443
  ```
