### ISSUE TITLE
Release 2.12.06 unable to connect to USB Device.

### ISSUE THREAD

**Issue by Stubbs** [marthoc/docker-deconz#418]
(I've seen the previous report for 2.12.04, and according to the upstream that was fixed in 2.12.5, and applying the suggested fix from that report doesn't fix this either.)

In the log I'm seeing repeated instances of `dev can't create file: /dev/ttyUSB0 via mknod (missing permissions)` and `dev can't create file: /dev/ttyACM0 via mknod (missing permissions)` even though the user I'm running docker as is a member of the dialout group, though I thought that was for read/write not creating ports? Also, neither of them are the port deconz should be using anyway.

I have my conbee II mapped to /dev/conbee using udev because I also have a z-wave USB dongle attached and they fight over whichs gets ttyACM0 and ttyACM1. At the moment the conbee II is ttyACM1.

This is my docker-compose config:

```
  deconz:
    image: marthoc/deconz
    container_name: deconz
    network_mode: host
    restart: always
    volumes:
      - ./deconz:/root/.local/share/dresden-elektronik/deCONZ
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/conbee:/dev/conbee
    environment:
      - DECONZ_WEB_PORT=8079
      - DECONZ_WS_PORT=8443
      - DECONZ_DEVICE=/dev/conbee
      - DEBUG_INFO=1
      - DECONZ_VNC_MODE=1
```

![image](https://user-images.githubusercontent.com/43525/130462758-2abe1bef-50dd-40f4-a13f-d72365e01931.png)

The most recent log file: [deconz.log](https://github.com/marthoc/docker-deconz/files/7032630/deconz.log)
