### ISSUE TITLE
No date and timezone shown in Phoscon app by default

### ISSUE THREAD

**Issue by hoblins** [marthoc/docker-deconz#436]
At first time logging into Phoscon app the in the advanced settings of the gateway the sections "Date", "Time" and "Timezone" are empty until the timezone is set manually with the button "Change timezone".

I would expect, that the timezone and date is set based on the settings passed to the container.

Docker compose file:
```
version: "3.7"

services:
  deconz:
    container_name: deconz
    image: marthoc/deconz:latest
    volumes:
       - /etc/localtime:/etc/localtime:ro
       - /opt/docker-data/deconz:/root/.local/share/dresden-elektronik/deCONZ
    restart: always
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - TZ=Europe/Berlin
      - DECONZ_WEB_PORT=80
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DECONZ_DEVICE=/dev/ttyACM0
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PASSWORD=
    networks:
      default:
        ipv4_address: XXX
        ipv6_address: XXX
    ports:
      - "80:80"
      - "443:443"
      - "5900:5900"
      - "6080:6080"
```

OS: Debian 10.11
Hardware: Conbee II
