### ISSUE TITLE
RPi with RaspBee and NUC with Conbee on the same network, Phoscon confused?

### ISSUE THREAD

**Issue by jantje88** [marthoc/docker-deconz#57]
I am using a RaspBee on a RPi 3B+ and want to migrate to a NUC with Conbee.

http://192.168.1.162 = NUC
http://192.168.1.163 = Raspberry Pi

After installing the HASS and DeCONZ dockers on the NUC and opening the Phoscon app on the NUC @ http://192.168.1.162:8383/pwa/ it shows two gateways: https://i.imgur.com/kZgX4kU.png

When logging on the to Phoscon app on the NUC (http://192.168.1.162:8383), it shows the RaspBee as connected product: https://i.imgur.com/q6UkLqX.png (But: no lights, switches, sensors are visible)

Is the Phocon app confused because there are two gateways on the same network?
The Conbee is on ttyUSB1 because another USB device (USB/P1 port for DSMR smart meter) is using ttyUSB0.

My docker compose to start the DeCONZ docker on the NUC:

```
  deconz:
    image: marthoc/deconz
    container_name: deconz
    network_mode: host
    restart: always  
    volumes:
      - /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyUSB1
    environment:
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DECONZ_DEVICE=/dev/ttyUSB1
      - DECONZ_WEB_PORT=8383
      - DECONZ_WS_PORT=8444
```

DeCONZ on HASS.io on the Raspberry Pi is using other ports: https://i.imgur.com/RZ00FYG.png

Also after shutting down the Raspberry Pi with RaspBee and resetting the gateway (Phoscon-GW) on the NUC, the Phoscon app on the NUC keeps telling me a RaspBee is connected..
