### ISSUE TITLE
Updating the DeCONZ docker

### ISSUE THREAD

**Issue by JBS5** [marthoc/docker-deconz#77]
Updating a docker should be as easy as deleting the old container, pull the latest en run the docker compose command. But I'm a little bit scared to do this because a lot of lights and sensors are connected and I don't want to lose them.  Before I was using the Hass.io add-on and updating was a done with only one click, now I want to ensure I am doing the right things and understand what I am doing. Several questions to reassure myself:

**1. Files and Phoscon back-up**
- My docker-compose below, meaning that the important files are stored in /opt/deconz? 
- These files contains all connected zigbee nodes and the network information? What is in these files and what is in the Phoscon back-up file? 

- Both are needed in case of emergency?
![](https://i.imgur.com/zQMjQNw.png)

- Quite related to this: I have installed the DeCONZ software on my Windows laptop and restored a Phoscon back-up, Switches and sensors are there again, but the light list is empty. Any clue why?

```
  deconz:
    image: marthoc/deconz
    container_name: deconz
    network_mode: host
    restart: always  
    volumes:
      - /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyUSB0
    environment:
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DECONZ_DEVICE=/dev/ttyUSB0
      - DECONZ_WEB_PORT=8383
      - DECONZ_WS_PORT=8444
```
**2. Docker** 
I prefer using Portainer to manage existing docker container. Do I need to stop and remove this container?

![](https://i.imgur.com/0k9Sbv4.png)

Something needed with the existing DeCONZ image?

![](https://i.imgur.com/eTL08RS.png)

What's next? Running the docker compose as above? None if my zigbee network/nodes or any other neeeded information is in the docker container/image?
