### ISSUE TITLE
2.5.58 Enable firmware updates in Phoscon App when deCONZ is running via Hass.io

### ISSUE THREAD

**Issue by lubbertkramer** [marthoc/docker-deconz#99]
In the latest version 2.5.58 it's possible to update the firmware with the hassio addons. Because you also maintain/ support that one is it possible this can also be done with the docker image ?

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1196

**Comment by lubbertkramer** [comment]
Thanks @marthoc for the update!

**Comment by marthoc** [comment]
So here's a question: if you create the container with the additional options: --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys
Could you then update firmware via the UI? All the core hass.io add-on is doing is giving more privileges and mount points to the container. Those commands above are the additional commands that are passed when using my firmware update script.

**Comment by lubbertkramer** [comment]
I will give it a try this weekend, will come back to this question

**Comment by lubbertkramer** [comment]
Not sure how to add above options @marthoc ,i'm still a beginner with Docker could you advise? Below is my compose

`  deconz-conbee:
    container_name: deconz-conbee
    image: marthoc/deconz:latest
    network_mode: host
    #restart: always
    volumes:
      - ${BASE}/deconz-conbee:/root/.local/share/dresden-elektronik/deCONZ
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyUSB0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8383"]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - DECONZ_DEVICE=/dev/ttyUSB0
      - DECONZ_WEB_PORT=8383
      - DECONZ_WS_PORT=8444
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=5900
      - DECONZ_VNC_PASSWORD=${DECONZVNC}`

**Comment by flavio20002** [comment]
This is the corrent compose. But sadly the update from interface is still disabled. The message is:

**A new version is available. The update needs to be installed manually via Docker.**
I think they put a check in the software...

```
  deconz:
    build: './deconz'
    container_name: deconz
    restart: unless-stopped
    volumes:
      - deconz:/root/.local/share/dresden-elektronik/deCONZ
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /dev:/dev
      - /lib/modules:/lib/modules
      - /sys:/sys
    devices:
      - /dev/ttyS0
    ports:
      - "10001:10001"
      - "10002:10002"
      - "6000:6000"
    privileged: true
    cap_add:
      - ALL
    environment:
      - DECONZ_DEVICE=/dev/ttyS0
      - DECONZ_WEB_PORT=10001
      - DECONZ_WS_PORT=10002
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PASSWORD=xxxx
      - DECONZ_VNC_PORT=6000
```
